version: "3.3"
services:
  app:
    volumes:
      - ./:/app/
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    entrypoint: /bin/bash -c
    command:
      - uvicorn wallet:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/wallet
